# Generated by Django 4.0 on 2022-07-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schoolprofile_delete_schoolprofiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_bio',
            field=models.TextField(max_length=3000),
        ),
    ]
