# Generated by Django 4.0 on 2022-07-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_schoolprofile_school_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='name_of_school',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_bio',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('upadated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('narration', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(choices=[('FUNDING', 'Funding'), ('PAYMENT', 'Payment')], max_length=200)),
                ('transaction_status', models.CharField(choices=[('SUCCESSS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESSS', max_length=200)),
                ('paystacak_reference', models.CharField(max_length=200)),
                ('destination', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transact', to='core.schoolprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
