# Generated by Django 4.0 on 2022-07-12 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolprofile_recipient_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='paystacak_reference',
            new_name='paystack_reference',
        ),
    ]
