# Generated by Django 4.0 on 2022-07-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_transactions_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
