# Generated by Django 4.0 on 2022-07-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_transactions_paystack_reference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='coursematerial',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='programme',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='schoolpin',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='year',
            old_name='upadated_at',
            new_name='updated_at',
        ),
    ]
