# Generated by Django 4.0 on 2022-07-19 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schoolprofile_first_name_schoolprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='course',
            field=models.ManyToManyField(blank=True, null=True, to='core.Course'),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_of_study', to='core.year'),
        ),
    ]
