# Generated by Django 4.0 on 2022-07-19 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schoolprofile_course_schoolprofile_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
