# Generated by Django 4.0 on 2022-07-19 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_teacher_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolprofile',
            old_name='course_duration',
            new_name='duration',
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='then'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='duration',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=200, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='then'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='phonenumber'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programme'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
