# Generated by Django 4.0 on 2022-07-11 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('upadated_at', models.DateTimeField(auto_now=True)),
                ('name_of_school', models.CharField(max_length=300)),
                ('course_duration', models.IntegerField(default=3, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('school_bio', models.TextField(default='big Uniuyo', max_length=3000)),
                ('schools_map', models.FileField(blank=True, null=True, upload_to='then')),
                ('school_fees', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('wallet', models.DecimalField(decimal_places=2, max_digits=11, null=True)),
                ('currency', models.CharField(default='NGN', max_length=50, null=True)),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.programme')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='core.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SchoolProfiles',
        ),
    ]
