# Generated by Django 4.0 on 2022-07-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_teacher_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
